
services:

  database:
    image: "postgres:17.2-alpine"
    ports:
      - '127.0.0.1:5132:5432'
    environment:
      POSTGRES_PASSWORD: innalyze2024**
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d
      - ./gitignored.d:/gitignored.d


volumes:
  postgres-volume:
