name: InnAlyze
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - annotated-types=0.6.0
  - loguru=0.5.3
  - anyio=4.6.2
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - fastapi=0.112.2
  - idna=3.7
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.11.11
  - readline=8.2
  - setuptools=75.1.0
  - sniffio=1.3.0
  - sqlite=3.45.3
  - starlette=0.38.2
  - tk=8.6.14
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - alembic==1.14.0
      - attrs==24.3.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.0
      - click==8.1.8
      - distro==1.9.0
      - httptools==0.6.4
      - jiter==0.8.2
      - langchain==0.3.14
      - langchain-core==0.3.29
      - langchain-openai==0.2.14
      - langchain-text-splitters==0.3.4
      - langgraph==0.2.62
      - langgraph-checkpoint==2.0.9
      - langgraph-checkpoint-postgres==2.0.10
      - langgraph-sdk==0.1.51
      - langsmith==0.2.4
      - mako==1.3.8
      - markupsafe==3.0.2
      - msgpack==1.1.0
      - numpy==1.26.4
      - openai==1.58.1
      - psycopg==3.2.3
      - psycopg-binary==3.2.3
      - psycopg-pool==3.2.4
      - psycopg2-binary==2.9.10
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - regex==2024.11.6
      - requests-toolbelt==1.0.0
      - sqlalchemy==2.0.36
      - tiktoken==0.8.0
      - tqdm==4.67.1
      - urllib3==2.2.3
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - watchfiles==1.0.4
      - websockets==14.1
