name: Build & Deploy
on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app to prod
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          #key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USER }} # User of the server you want to ssh into
          password: ${{ secrets.SSH_KEY }}

          script: | 
            cd ~/projects/innalyze-agent
            echo '--- Deployment successful to Azure ocean PROD VM ---' 
            git checkout main
            docker-compose down
            git pull origin main
            #cp .env.prd .env
            docker-compose up -d


